//! `masked_claims` official-game crate skeleton for Masked Claims.

pub mod ids;

pub use ids::{
    canonical_masks, Grade, MaskTileId, MaskedClaimsSeat, ACTION_CLAIM, ACTION_RESPOND_ACCEPT,
    ACTION_RESPOND_CHALLENGE, GAME_ID, RULES_VERSION_LABEL, STANDARD_CLAIMS_PER_SEAT,
    STANDARD_GRADE_COUNT, STANDARD_HAND_SIZE, STANDARD_MASK_COUNT, STANDARD_MAX_TURNS,
    STANDARD_RESERVE_SIZE, STANDARD_SEAT_COUNT, STANDARD_TILES_PER_GRADE, VARIANT_ID,
};
