//! Browser-bridge helpers for `column_four` (perfect-information grid game).

use column_four::{
    apply_action as column_apply_action, project_view as column_project_view,
    replay_support::replay_commands as column_replay_commands, setup_match as column_setup_match,
    ColumnFourEffect, ColumnFourSeat, ColumnFourState,
};
use engine_core::{ActionPath, CommandEnvelope, EffectEnvelope, RulesVersion, Seed, Viewer};

use crate::actors::column_actor_for_seat;
use crate::commands::{command_record_json, single_segment_commands};
use crate::constants::*;
use crate::json::{diagnostic_json, escape_json};
use crate::seats::{parse_column_seat, seats, trace_column_seat};
use crate::{option_string_json, string_array, visibility_json, AppliedCommand};

pub(crate) fn column_replay_to_cursor(
    seed: u64,
    commands: &[AppliedCommand],
    cursor: usize,
) -> Result<(ColumnFourState, Vec<EffectEnvelope<ColumnFourEffect>>), String> {
    let seats = seats();
    let mut state = column_setup_match(Seed(seed), &seats, &column_four::SetupOptions::default())
        .map_err(diagnostic_json)?;
    let mut all_effects = Vec::new();
    for command in commands.iter().take(cursor) {
        let seat = parse_column_seat(&command.actor_seat)?;
        let envelope = CommandEnvelope {
            actor: column_actor_for_seat(&state, seat)?,
            action_path: ActionPath {
                segments: command.action_path.clone(),
            },
            freshness_token: engine_core::FreshnessToken(command.freshness_token),
            rules_version: RulesVersion(RULES_VERSION),
        };
        let action = column_four::validate_command(&state, &envelope).map_err(diagnostic_json)?;
        all_effects.extend(column_apply_action(&mut state, action));
    }
    Ok((state, all_effects))
}

pub(crate) fn column_effects_json(effects: &[EffectEnvelope<ColumnFourEffect>]) -> String {
    let body = effects
        .iter()
        .map(column_effect_json)
        .collect::<Vec<_>>()
        .join(",");
    format!("[{body}]")
}

pub(crate) fn column_replay_document_json(
    trace_id: &str,
    seed: u64,
    commands: &[AppliedCommand],
) -> Result<String, String> {
    let command_segments = single_segment_commands(commands)?;
    let hashes = column_replay_commands(seed, &command_segments);
    let commands_json = commands
        .iter()
        .enumerate()
        .map(|(index, command)| command_record_json(index, command))
        .collect::<Vec<_>>()
        .join(",");
    let checkpoints = if commands.is_empty() {
        "[{\"id\":\"final\",\"after_command_index\":0}]".to_owned()
    } else {
        format!(
            "[{{\"id\":\"final\",\"after_command_index\":{}}}]",
            commands.len().saturating_sub(1)
        )
    };
    let outcome = hashes.outcome.map_or_else(
        || "{\"terminal\":false,\"winner\":null,\"kind\":\"none\",\"draw\":false}".to_owned(),
        |outcome| match outcome {
            column_four::TerminalOutcome::Draw => {
                "{\"terminal\":true,\"winner\":null,\"kind\":\"draw\",\"draw\":true}".to_owned()
            }
            column_four::TerminalOutcome::Win { seat, line } => format!(
                "{{\"terminal\":true,\"winner\":\"{}\",\"kind\":\"win\",\"draw\":false,\"line\":[\"{}\",\"{}\",\"{}\",\"{}\"]}}",
                trace_column_seat(seat),
                line.cells[0].as_string(),
                line.cells[1].as_string(),
                line.cells[2].as_string(),
                line.cells[3].as_string()
            ),
        },
    );

    Ok(format!(
        "{{\"schema_version\":{},\"trace_id\":\"{}\",\"fixture_kind\":\"commands\",\"purpose\":\"wasm_exported_replay\",\"note\":\"Replay exported by the Rulepath WASM API from the Rust command log.\",\"migration_update_note\":\"Generated by Gate 5 WASM replay export; expected hashes are computed by Column Four Rust replay support.\",\"game_id\":\"{}\",\"rules_version\":\"{}\",\"engine_version\":\"{}\",\"data_version\":\"{}\",\"seed\":{},\"variant\":\"{}\",\"options\":{{}},\"seats\":[{{\"seat_id\":\"seat-0\",\"player_id\":\"player-0\"}},{{\"seat_id\":\"seat-1\",\"player_id\":\"player-1\"}}],\"commands\":[{}],\"checkpoints\":{},\"expected_state_hashes\":{{\"final\":{}}},\"expected_effect_hashes\":{{\"final\":{}}},\"expected_action_tree_hashes\":{{\"final\":{}}},\"expected_public_view_hashes\":{{\"all\":{}}},\"expected_private_view_hashes\":{{\"not_applicable\":\"column_four is perfect-information and has no private-view API.\"}},\"expected_replay_hashes\":{{\"final\":{}}},\"expected_outcome\":{},\"expected_terminal_state\":{},\"not_applicable\":{{\"hidden_information\":\"column_four is perfect-information and has no hidden state to redact.\",\"stochastic_game_events\":\"column_four game rules use no randomness; bot RNG is not replayed from exported documents because resolved commands are recorded.\",\"private_view_hashes\":\"column_four has no private-view API.\",\"preview_hashes\":\"column_four has no Rust preview surface in Gate 5.\"}}}}",
        SCHEMA_VERSION,
        escape_json(trace_id),
        escape_json(GAME_COLUMN_FOUR),
        escape_json(COLUMN_FOUR_TRACE_RULES_VERSION),
        escape_json(ENGINE_VERSION),
        escape_json(DATA_VERSION),
        seed,
        escape_json(VARIANT_COLUMN_FOUR_STANDARD),
        commands_json,
        checkpoints,
        hashes.state_hash.0,
        hashes.effect_hash.0,
        hashes.action_tree_hash.0,
        hashes.view_hash.0,
        hashes.replay_hash.0,
        outcome,
        outcome
    ))
}

pub(crate) fn column_replay_step_json(
    replay_id: &str,
    cursor: usize,
    command_count: usize,
    state: &ColumnFourState,
    effects: &[EffectEnvelope<ColumnFourEffect>],
) -> String {
    format!(
        "{{\"replay_id\":\"{}\",\"cursor\":{},\"command_count\":{},\"done\":{},\"view\":{},\"effects\":{}}}",
        escape_json(replay_id),
        cursor,
        command_count,
        cursor >= command_count,
        column_view_json(&column_project_view(state, &Viewer { seat_id: None })),
        column_effects_json(effects)
    )
}

pub(crate) fn column_view_json(view: &column_four::PublicView) -> String {
    format!(
        "{{\"schema_version\":{},\"rules_version\":{},\"game_id\":\"{}\",\"display_name\":\"{}\",\"variant_id\":\"{}\",\"rules_version_label\":\"{}\",\"board_rows\":{},\"board_columns\":{},\"cells\":[{}],\"columns\":[{}],\"active_seat\":{},\"ply_count\":{},\"status_label\":\"{}\",\"freshness_token\":{},\"legal_targets\":[{}],\"terminal_kind\":\"{}\",\"winning_seat\":{},\"winning_line\":[{}],\"private_view_status\":\"{}\",\"hidden_fields\":[{}],\"replay_step_index\":{}}}",
        view.schema_version,
        view.rules_version,
        escape_json(&view.game_id),
        escape_json(&view.display_name),
        escape_json(&view.variant_id),
        escape_json(&view.rules_version_label),
        view.board_rows,
        view.board_columns,
        view.cells
            .iter()
            .map(column_cell_json)
            .collect::<Vec<_>>()
            .join(","),
        view.columns
            .iter()
            .map(column_summary_json)
            .collect::<Vec<_>>()
            .join(","),
        option_column_seat_json(view.active_seat),
        view.ply_count,
        escape_json(&view.status_label),
        view.freshness_token.0,
        view.legal_targets
            .iter()
            .map(column_legal_target_json)
            .collect::<Vec<_>>()
            .join(","),
        column_terminal_kind(&view.terminal),
        option_column_seat_json(column_terminal_winner(&view.terminal)),
        string_array(&column_terminal_line(&view.terminal)),
        escape_json(&view.private_view.status),
        string_array(&view.private_view.hidden_fields),
        view.replay_step_index
            .map_or_else(|| "null".to_owned(), |step| step.to_string())
    )
}

pub(crate) fn column_cell_json(cell: &column_four::CellView) -> String {
    format!(
        "{{\"cell\":\"{}\",\"row\":{},\"column\":{},\"occupancy\":\"{}\",\"owner\":{},\"piece_token_key\":{},\"piece_shape_label\":{}}}",
        cell.cell.as_string(),
        cell.row,
        cell.column,
        escape_json(&cell.occupancy),
        option_column_seat_json(cell.owner),
        option_string_json(cell.piece_token_key.as_deref()),
        option_string_json(cell.piece_shape_label.as_deref())
    )
}

pub(crate) fn column_summary_json(column: &column_four::ColumnSummaryView) -> String {
    format!(
        "{{\"column\":\"{}\",\"column_id\":\"{}\",\"label\":\"{}\",\"is_full\":{},\"legal_action_segment\":{},\"landing_preview\":{}}}",
        column.column.as_str(),
        escape_json(&column.column_id),
        escape_json(&column.label),
        column.is_full,
        option_string_json(column.legal_action_segment.as_deref()),
        option_cell_json(column.landing_preview)
    )
}

pub(crate) fn column_legal_target_json(target: &column_four::LegalColumnTargetView) -> String {
    format!(
        "{{\"column\":\"{}\",\"action_segment\":\"{}\",\"label\":\"{}\",\"accessibility_label\":\"{}\",\"freshness_token\":{},\"landing_preview\":\"{}\"}}",
        target.column.as_str(),
        escape_json(&target.action_segment),
        escape_json(&target.label),
        escape_json(&target.accessibility_label),
        target.freshness_token.0,
        target.landing_preview.as_string()
    )
}

pub(crate) fn column_effect_json(effect: &EffectEnvelope<ColumnFourEffect>) -> String {
    let payload = match &effect.payload {
        ColumnFourEffect::DropAccepted { seat, column, ply } => format!(
            "{{\"type\":\"drop_accepted\",\"seat\":\"{}\",\"column\":\"{}\",\"ply\":{}}}",
            seat.as_str(),
            column.as_str(),
            ply
        ),
        ColumnFourEffect::PieceLanded {
            seat,
            column,
            row,
            cell,
            display_from_anchor,
            display_to_anchor,
        } => format!(
            "{{\"type\":\"piece_landed\",\"seat\":\"{}\",\"column\":\"{}\",\"row\":\"{}\",\"cell\":\"{}\",\"display_from_anchor\":\"{}\",\"display_to_anchor\":\"{}\"}}",
            seat.as_str(),
            column.as_str(),
            row.as_str(),
            cell.as_string(),
            escape_json(display_from_anchor),
            escape_json(display_to_anchor)
        ),
        ColumnFourEffect::ActivePlayerChanged {
            previous_seat,
            active_seat,
            ply,
        } => format!(
            "{{\"type\":\"active_player_changed\",\"previous_seat\":\"{}\",\"active_seat\":\"{}\",\"ply\":{}}}",
            previous_seat.as_str(),
            active_seat.as_str(),
            ply
        ),
        ColumnFourEffect::WinDetected { winning_seat, line } => format!(
            "{{\"type\":\"win_detected\",\"winning_seat\":\"{}\",\"line\":[\"{}\",\"{}\",\"{}\",\"{}\"]}}",
            winning_seat.as_str(),
            line.cells[0].as_string(),
            line.cells[1].as_string(),
            line.cells[2].as_string(),
            line.cells[3].as_string()
        ),
        ColumnFourEffect::DrawDetected {
            final_ply,
            full_board,
        } => format!(
            "{{\"type\":\"draw_detected\",\"final_ply\":{},\"full_board\":{}}}",
            final_ply, full_board
        ),
        ColumnFourEffect::GameEnded {
            outcome,
            final_ply,
            terminal_hash_ref,
        } => format!(
            "{{\"type\":\"game_ended\",\"outcome\":{},\"final_ply\":{},\"terminal_hash_ref\":\"{}\"}}",
            column_terminal_outcome_json(*outcome),
            final_ply,
            escape_json(terminal_hash_ref)
        ),
        ColumnFourEffect::BotChoseAction {
            level,
            policy_id,
            action_id,
            column,
            rationale,
        } => format!(
            "{{\"type\":\"bot_chose_action\",\"level\":{},\"policy_id\":\"{}\",\"action_id\":\"{}\",\"column\":\"{}\",\"rationale\":\"{}\"}}",
            level,
            escape_json(policy_id),
            escape_json(action_id),
            column.as_str(),
            escape_json(rationale)
        ),
    };
    format!(
        "{{\"visibility\":{},\"payload\":{}}}",
        visibility_json(&effect.visibility),
        payload
    )
}

pub(crate) fn column_terminal_kind(terminal: &column_four::TerminalView) -> &'static str {
    match terminal {
        column_four::TerminalView::NonTerminal => "non_terminal",
        column_four::TerminalView::Win { .. } => "win",
        column_four::TerminalView::Draw { .. } => "draw",
    }
}

pub(crate) fn column_terminal_winner(
    terminal: &column_four::TerminalView,
) -> Option<ColumnFourSeat> {
    match terminal {
        column_four::TerminalView::Win { winning_seat, .. } => Some(*winning_seat),
        _ => None,
    }
}

pub(crate) fn column_terminal_line(terminal: &column_four::TerminalView) -> Vec<String> {
    match terminal {
        column_four::TerminalView::Win { line, .. } => {
            line.iter().map(|cell| cell.as_string()).collect()
        }
        _ => Vec::new(),
    }
}

pub(crate) fn column_terminal_outcome_json(outcome: column_four::TerminalOutcome) -> String {
    match outcome {
        column_four::TerminalOutcome::Draw => "{\"kind\":\"draw\"}".to_owned(),
        column_four::TerminalOutcome::Win { seat, line } => format!(
            "{{\"kind\":\"win\",\"seat\":\"{}\",\"line\":[\"{}\",\"{}\",\"{}\",\"{}\"]}}",
            seat.as_str(),
            line.cells[0].as_string(),
            line.cells[1].as_string(),
            line.cells[2].as_string(),
            line.cells[3].as_string()
        ),
    }
}

pub(crate) fn option_column_seat_json(seat: Option<ColumnFourSeat>) -> String {
    seat.map_or_else(
        || "null".to_owned(),
        |seat| format!("\"{}\"", seat.as_str()),
    )
}

fn option_cell_json(cell: Option<column_four::CellId>) -> String {
    cell.map_or_else(
        || "null".to_owned(),
        |cell| format!("\"{}\"", cell.as_string()),
    )
}
