//! Browser-bridge helpers for `directional_flip` (perfect-information grid game).

use directional_flip::{
    apply_action as directional_apply_action, project_view as directional_project_view,
    replay_support::replay_commands as directional_replay_commands,
    setup_match as directional_setup_match, DirectionalFlipEffect, DirectionalFlipSeat,
    DirectionalFlipState,
};
use engine_core::{ActionPath, CommandEnvelope, EffectEnvelope, RulesVersion, Seed, Viewer};

use crate::actors::directional_actor_for_seat;
use crate::commands::{command_record_json, single_segment_commands};
use crate::constants::*;
use crate::json::{diagnostic_json, escape_json};
use crate::seats::{parse_directional_seat, seats, trace_directional_seat};
use crate::{option_string_json, string_array, visibility_json, AppliedCommand};

pub(crate) fn directional_replay_to_cursor(
    seed: u64,
    commands: &[AppliedCommand],
    cursor: usize,
) -> Result<
    (
        DirectionalFlipState,
        Vec<EffectEnvelope<DirectionalFlipEffect>>,
    ),
    String,
> {
    let seats = seats();
    let mut state = directional_setup_match(
        Seed(seed),
        &seats,
        &directional_flip::SetupOptions::default(),
    )
    .map_err(diagnostic_json)?;
    let mut all_effects = Vec::new();
    for command in commands.iter().take(cursor) {
        let seat = parse_directional_seat(&command.actor_seat)?;
        let envelope = CommandEnvelope {
            actor: directional_actor_for_seat(&state, seat)?,
            action_path: ActionPath {
                segments: command.action_path.clone(),
            },
            freshness_token: engine_core::FreshnessToken(command.freshness_token),
            rules_version: RulesVersion(RULES_VERSION),
        };
        let action =
            directional_flip::validate_command(&state, &envelope).map_err(diagnostic_json)?;
        all_effects.extend(directional_apply_action(&mut state, action));
    }
    Ok((state, all_effects))
}

pub(crate) fn directional_effects_json(
    effects: &[EffectEnvelope<DirectionalFlipEffect>],
) -> String {
    let body = effects
        .iter()
        .map(directional_effect_json)
        .collect::<Vec<_>>()
        .join(",");
    format!("[{body}]")
}

pub(crate) fn directional_replay_document_json(
    trace_id: &str,
    seed: u64,
    commands: &[AppliedCommand],
) -> Result<String, String> {
    let command_segments = single_segment_commands(commands)?;
    let hashes = directional_replay_commands(seed, &command_segments);
    let commands_json = commands
        .iter()
        .enumerate()
        .map(|(index, command)| command_record_json(index, command))
        .collect::<Vec<_>>()
        .join(",");
    let checkpoints = if commands.is_empty() {
        "[{\"id\":\"final\",\"after_command_index\":0}]".to_owned()
    } else {
        format!(
            "[{{\"id\":\"final\",\"after_command_index\":{}}}]",
            commands.len().saturating_sub(1)
        )
    };
    let outcome = hashes.outcome.map_or_else(
        || "{\"terminal\":false,\"winner\":null,\"kind\":\"none\",\"draw\":false}".to_owned(),
        |outcome| match outcome {
            directional_flip::TerminalOutcome::Draw => {
                "{\"terminal\":true,\"winner\":null,\"kind\":\"draw\",\"draw\":true}".to_owned()
            }
            directional_flip::TerminalOutcome::Win { seat } => format!(
                "{{\"terminal\":true,\"winner\":\"{}\",\"kind\":\"win\",\"draw\":false}}",
                trace_directional_seat(seat)
            ),
        },
    );

    Ok(format!(
        "{{\"schema_version\":{},\"trace_id\":\"{}\",\"fixture_kind\":\"commands\",\"purpose\":\"wasm_exported_replay\",\"note\":\"Replay exported by the Rulepath WASM API from the Rust command log.\",\"migration_update_note\":\"Generated by Gate 6 WASM replay export; expected hashes are computed by Directional Flip Rust replay support.\",\"game_id\":\"{}\",\"rules_version\":\"{}\",\"engine_version\":\"{}\",\"data_version\":\"{}\",\"seed\":{},\"variant\":\"{}\",\"options\":{{}},\"seats\":[{{\"seat_id\":\"seat-0\",\"player_id\":\"player-0\"}},{{\"seat_id\":\"seat-1\",\"player_id\":\"player-1\"}}],\"commands\":[{}],\"checkpoints\":{},\"expected_state_hashes\":{{\"final\":{}}},\"expected_effect_hashes\":{{\"final\":{}}},\"expected_action_tree_hashes\":{{\"final\":{}}},\"expected_public_view_hashes\":{{\"all\":{}}},\"expected_private_view_hashes\":{{\"not_applicable\":\"directional_flip is perfect-information and has no private-view API.\"}},\"expected_replay_hashes\":{{\"final\":{}}},\"expected_outcome\":{},\"expected_terminal_state\":{},\"not_applicable\":{{\"hidden_information\":\"directional_flip is perfect-information and has no hidden state to redact.\",\"stochastic_game_events\":\"directional_flip game rules use no randomness; bot RNG is not replayed from exported documents because resolved commands are recorded.\",\"private_view_hashes\":\"directional_flip has no private-view API.\"}}}}",
        SCHEMA_VERSION,
        escape_json(trace_id),
        escape_json(GAME_DIRECTIONAL_FLIP),
        escape_json(DIRECTIONAL_FLIP_TRACE_RULES_VERSION),
        escape_json(ENGINE_VERSION),
        escape_json(DATA_VERSION),
        seed,
        escape_json(VARIANT_DIRECTIONAL_FLIP_STANDARD),
        commands_json,
        checkpoints,
        hashes.state_hash.0,
        hashes.effect_hash.0,
        hashes.action_tree_hash.0,
        hashes.view_hash.0,
        hashes.replay_hash.0,
        outcome,
        outcome
    ))
}

pub(crate) fn directional_replay_step_json(
    replay_id: &str,
    cursor: usize,
    command_count: usize,
    state: &DirectionalFlipState,
    effects: &[EffectEnvelope<DirectionalFlipEffect>],
) -> String {
    format!(
        "{{\"replay_id\":\"{}\",\"cursor\":{},\"command_count\":{},\"done\":{},\"view\":{},\"effects\":{}}}",
        escape_json(replay_id),
        cursor,
        command_count,
        cursor >= command_count,
        directional_view_json(&directional_project_view(state, &Viewer { seat_id: None })),
        directional_effects_json(effects)
    )
}

pub(crate) fn directional_view_json(view: &directional_flip::PublicView) -> String {
    format!(
        "{{\"schema_version\":{},\"rules_version\":{},\"game_id\":\"{}\",\"display_name\":\"{}\",\"variant_id\":\"{}\",\"rules_version_label\":\"{}\",\"board_rows\":{},\"board_columns\":{},\"cells\":[{}],\"active_seat\":{},\"ply_count\":{},\"status_label\":\"{}\",\"freshness_token\":{},\"score\":{},\"legal_targets\":[{}],\"terminal_kind\":\"{}\",\"winning_seat\":{},\"final_score\":{},\"private_view_status\":\"{}\",\"hidden_fields\":[{}],\"ui\":{},\"last_action_summary\":{},\"bot_rationale\":{},\"replay_step_index\":{}}}",
        view.schema_version,
        view.rules_version,
        escape_json(&view.game_id),
        escape_json(&view.display_name),
        escape_json(&view.variant_id),
        escape_json(&view.rules_version_label),
        view.board_rows,
        view.board_columns,
        view.cells
            .iter()
            .map(directional_cell_json)
            .collect::<Vec<_>>()
            .join(","),
        option_directional_seat_json(view.active_seat),
        view.ply_count,
        escape_json(&view.status_label),
        view.freshness_token.0,
        directional_score_view_json(&view.score),
        view.legal_targets
            .iter()
            .map(directional_legal_target_json)
            .collect::<Vec<_>>()
            .join(","),
        directional_terminal_kind(&view.terminal),
        option_directional_seat_json(directional_terminal_winner(&view.terminal)),
        directional_terminal_score_json(&view.terminal),
        escape_json(&view.private_view.status),
        string_array(&view.private_view.hidden_fields),
        directional_ui_json(&view.ui),
        option_string_json(view.last_action_summary.as_deref()),
        option_string_json(view.bot_rationale.as_deref()),
        view.replay_step_index
            .map_or_else(|| "null".to_owned(), |step| step.to_string())
    )
}

pub(crate) fn directional_cell_json(cell: &directional_flip::CellView) -> String {
    format!(
        "{{\"cell\":\"{}\",\"cell_id\":\"{}\",\"row\":{},\"column\":{},\"occupancy\":\"{}\",\"owner\":{},\"disc_token_key\":{},\"disc_shape_label\":{},\"disc_pattern_label\":{}}}",
        cell.cell.as_string(),
        escape_json(&cell.cell_id),
        cell.row,
        cell.column,
        escape_json(&cell.occupancy),
        option_directional_seat_json(cell.owner),
        option_string_json(cell.disc_token_key.as_deref()),
        option_string_json(cell.disc_shape_label.as_deref()),
        option_string_json(cell.disc_pattern_label.as_deref())
    )
}

pub(crate) fn directional_legal_target_json(target: &directional_flip::LegalTargetView) -> String {
    format!(
        "{{\"action_kind\":\"{}\",\"action_segment\":\"{}\",\"label\":\"{}\",\"accessibility_label\":\"{}\",\"freshness_token\":{},\"cell\":{},\"preview\":{},\"reason_code\":{},\"explanation\":\"{}\"}}",
        escape_json(&target.action_kind),
        escape_json(&target.action_segment),
        escape_json(&target.label),
        escape_json(&target.accessibility_label),
        target.freshness_token.0,
        option_directional_cell_json(target.cell),
        target
            .preview
            .as_ref()
            .map_or_else(|| "null".to_owned(), directional_preview_json),
        option_string_json(target.reason_code.as_deref()),
        escape_json(&target.explanation)
    )
}

pub(crate) fn directional_preview_json(preview: &directional_flip::PlacementPreviewView) -> String {
    format!(
        "{{\"preview_id\":\"{}\",\"target_cell\":\"{}\",\"target_cell_id\":\"{}\",\"row\":{},\"column\":{},\"ordered_flip_cells\":[{}],\"ordered_flip_cell_ids\":[{}],\"direction_groups\":[{}],\"explanation\":\"{}\"}}",
        escape_json(&preview.preview_id),
        preview.target_cell.as_string(),
        escape_json(&preview.target_cell_id),
        preview.row,
        preview.column,
        directional_cell_array_json(&preview.ordered_flip_cells),
        string_array(&preview.ordered_flip_cell_ids),
        preview
            .direction_groups
            .iter()
            .map(directional_group_json)
            .collect::<Vec<_>>()
            .join(","),
        escape_json(&preview.explanation)
    )
}

pub(crate) fn directional_group_json(
    group: &directional_flip::visibility::DirectionGroupView,
) -> String {
    format!(
        "{{\"direction\":\"{}\",\"cells\":[{}],\"cell_ids\":[{}]}}",
        escape_json(&group.direction),
        directional_cell_array_json(&group.cells),
        string_array(&group.cell_ids)
    )
}

pub(crate) fn directional_ui_json(ui: &directional_flip::UiMetadata) -> String {
    format!(
        "{{\"board_label\":\"{}\",\"row_count\":{},\"column_count\":{},\"first_disc_token_key\":\"{}\",\"first_disc_shape_label\":\"{}\",\"first_disc_pattern_label\":\"{}\",\"second_disc_token_key\":\"{}\",\"second_disc_shape_label\":\"{}\",\"second_disc_pattern_label\":\"{}\",\"legal_target_shape_label\":\"{}\",\"forced_pass_label\":\"{}\"}}",
        escape_json(&ui.board_label),
        ui.row_count,
        ui.column_count,
        escape_json(&ui.first_disc_token_key),
        escape_json(&ui.first_disc_shape_label),
        escape_json(&ui.first_disc_pattern_label),
        escape_json(&ui.second_disc_token_key),
        escape_json(&ui.second_disc_shape_label),
        escape_json(&ui.second_disc_pattern_label),
        escape_json(&ui.legal_target_shape_label),
        escape_json(&ui.forced_pass_label)
    )
}

pub(crate) fn directional_effect_json(effect: &EffectEnvelope<DirectionalFlipEffect>) -> String {
    let payload = match &effect.payload {
        DirectionalFlipEffect::PlacementAccepted { seat, cell, ply } => format!(
            "{{\"type\":\"placement_accepted\",\"seat\":\"{}\",\"cell\":\"{}\",\"ply\":{}}}",
            seat.as_str(),
            cell.as_string(),
            ply
        ),
        DirectionalFlipEffect::DiscPlaced {
            seat,
            cell,
            display_to_anchor,
        } => format!(
            "{{\"type\":\"disc_placed\",\"seat\":\"{}\",\"cell\":\"{}\",\"display_to_anchor\":\"{}\"}}",
            seat.as_str(),
            cell.as_string(),
            escape_json(display_to_anchor)
        ),
        DirectionalFlipEffect::DiscsFlipped { seat, flips } => format!(
            "{{\"type\":\"discs_flipped\",\"seat\":\"{}\",\"flips\":[{}]}}",
            seat.as_str(),
            flips
                .iter()
                .map(directional_flip_entry_json)
                .collect::<Vec<_>>()
                .join(",")
        ),
        DirectionalFlipEffect::PassTaken { seat, ply, reason } => format!(
            "{{\"type\":\"pass_taken\",\"seat\":\"{}\",\"ply\":{},\"reason\":\"{}\"}}",
            seat.as_str(),
            ply,
            escape_json(reason)
        ),
        DirectionalFlipEffect::ActivePlayerChanged {
            previous_seat,
            active_seat,
            ply,
        } => format!(
            "{{\"type\":\"active_player_changed\",\"previous_seat\":\"{}\",\"active_seat\":\"{}\",\"ply\":{}}}",
            previous_seat.as_str(),
            active_seat.as_str(),
            ply
        ),
        DirectionalFlipEffect::GameEnded {
            outcome,
            final_score,
            final_ply,
            reason,
            ..
        } => format!(
            "{{\"type\":\"game_ended\",\"outcome\":{},\"final_score\":{},\"final_ply\":{},\"reason\":\"{}\"}}",
            directional_terminal_outcome_json(*outcome),
            directional_score_json(*final_score),
            final_ply,
            directional_terminal_reason(*reason)
        ),
        DirectionalFlipEffect::BotChoseAction {
            level,
            policy_id,
            action_id,
            rationale,
        } => format!(
            "{{\"type\":\"bot_chose_action\",\"level\":{},\"policy_id\":\"{}\",\"action_id\":\"{}\",\"rationale\":\"{}\"}}",
            level,
            escape_json(policy_id),
            escape_json(action_id),
            escape_json(rationale)
        ),
    };
    format!(
        "{{\"visibility\":{},\"payload\":{}}}",
        visibility_json(&effect.visibility),
        payload
    )
}

pub(crate) fn directional_flip_entry_json(flip: &directional_flip::FlipEntry) -> String {
    format!(
        "{{\"cell\":\"{}\",\"previous_owner\":\"{}\",\"new_owner\":\"{}\",\"direction\":\"{}\",\"distance\":{},\"order_index\":{},\"display_anchor\":\"{}\"}}",
        flip.cell.as_string(),
        flip.previous_owner.as_str(),
        flip.new_owner.as_str(),
        flip.direction.as_str(),
        flip.distance,
        flip.order_index,
        escape_json(&flip.display_anchor)
    )
}

pub(crate) fn directional_terminal_kind(terminal: &directional_flip::TerminalView) -> &'static str {
    match terminal {
        directional_flip::TerminalView::NonTerminal => "non_terminal",
        directional_flip::TerminalView::Win { .. } => "win",
        directional_flip::TerminalView::Draw { .. } => "draw",
    }
}

pub(crate) fn directional_terminal_winner(
    terminal: &directional_flip::TerminalView,
) -> Option<DirectionalFlipSeat> {
    match terminal {
        directional_flip::TerminalView::Win { winning_seat, .. } => Some(*winning_seat),
        _ => None,
    }
}

pub(crate) fn directional_terminal_score_json(terminal: &directional_flip::TerminalView) -> String {
    match terminal {
        directional_flip::TerminalView::NonTerminal => "null".to_owned(),
        directional_flip::TerminalView::Win { final_score, .. }
        | directional_flip::TerminalView::Draw { final_score, .. } => {
            directional_score_view_json(final_score)
        }
    }
}

pub(crate) fn directional_terminal_outcome_json(
    outcome: directional_flip::TerminalOutcome,
) -> String {
    match outcome {
        directional_flip::TerminalOutcome::Draw => "{\"kind\":\"draw\"}".to_owned(),
        directional_flip::TerminalOutcome::Win { seat } => {
            format!("{{\"kind\":\"win\",\"seat\":\"{}\"}}", seat.as_str())
        }
    }
}

pub(crate) fn directional_terminal_reason(
    reason: directional_flip::TerminalReason,
) -> &'static str {
    match reason {
        directional_flip::TerminalReason::BoardFull => "board_full",
        directional_flip::TerminalReason::NoContinuation => "no_continuation",
        directional_flip::TerminalReason::DoubleForcedPass => "double_forced_pass",
    }
}

pub(crate) fn directional_score_json(score: directional_flip::Score) -> String {
    format!(
        "{{\"seat_0\":{},\"seat_1\":{}}}",
        score.seat_0, score.seat_1
    )
}

pub(crate) fn directional_score_view_json(score: &directional_flip::ScoreView) -> String {
    format!(
        "{{\"seat_0\":{},\"seat_1\":{}}}",
        score.seat_0, score.seat_1
    )
}

pub(crate) fn option_directional_seat_json(seat: Option<DirectionalFlipSeat>) -> String {
    seat.map_or_else(
        || "null".to_owned(),
        |seat| format!("\"{}\"", seat.as_str()),
    )
}

pub(crate) fn option_directional_cell_json(cell: Option<directional_flip::CellId>) -> String {
    cell.map_or_else(
        || "null".to_owned(),
        |cell| format!("\"{}\"", cell.as_string()),
    )
}

pub(crate) fn directional_cell_array_json(values: &[directional_flip::CellId]) -> String {
    values
        .iter()
        .map(|cell| format!("\"{}\"", cell.as_string()))
        .collect::<Vec<_>>()
        .join(",")
}
