//! Browser-bridge helpers for `race_to_n` (perfect-information counter race).

use engine_core::{
    ActionPath, CommandEnvelope, EffectEnvelope, RulesVersion, Seed, VisibilityScope,
};
use race_to_n::{
    apply_action as race_apply_action, project_view,
    replay_support::replay_commands as race_replay_commands, setup_match as race_setup_match,
    RaceEffect, RaceState, SetupOptions as RaceSetupOptions,
};

use crate::actors::race_actor_for_seat;
use crate::commands::{command_record_json, single_segment_commands};
use crate::constants::*;
use crate::json::{diagnostic_json, escape_json};
use crate::seats::{parse_replay_race_seat, seats};
use crate::AppliedCommand;

pub(crate) fn race_replay_to_cursor(
    seed: u64,
    commands: &[AppliedCommand],
    cursor: usize,
) -> Result<(RaceState, Vec<EffectEnvelope<RaceEffect>>), String> {
    let seats = seats();
    let mut state = race_setup_match(Seed(seed), &seats, &RaceSetupOptions::default())
        .map_err(diagnostic_json)?;
    let mut all_effects = Vec::new();
    for command in commands.iter().take(cursor) {
        let seat = parse_replay_race_seat(&command.actor_seat)?;
        let envelope = CommandEnvelope {
            actor: race_actor_for_seat(&state, seat)?,
            action_path: ActionPath {
                segments: command.action_path.clone(),
            },
            freshness_token: engine_core::FreshnessToken(command.freshness_token),
            rules_version: RulesVersion(RULES_VERSION),
        };
        let action = race_to_n::validate_command(&state, &envelope).map_err(diagnostic_json)?;
        all_effects.extend(race_apply_action(&mut state, action));
    }
    Ok((state, all_effects))
}

pub(crate) fn race_effects_json(effects: &[EffectEnvelope<RaceEffect>]) -> String {
    let body = effects
        .iter()
        .map(race_effect_json)
        .collect::<Vec<_>>()
        .join(",");
    format!("[{body}]")
}

pub(crate) fn race_replay_document_json(
    trace_id: &str,
    seed: u64,
    commands: &[AppliedCommand],
) -> Result<String, String> {
    let command_segments = single_segment_commands(commands)?;
    let hashes = race_replay_commands(seed, &command_segments);
    let commands_json = commands
        .iter()
        .enumerate()
        .map(|(index, command)| command_record_json(index, command))
        .collect::<Vec<_>>()
        .join(",");
    let checkpoints = if commands.is_empty() {
        "[{\"id\":\"final\",\"after_command_index\":0}]".to_owned()
    } else {
        format!(
            "[{{\"id\":\"final\",\"after_command_index\":{}}}]",
            commands.len().saturating_sub(1)
        )
    };
    let terminal = hashes.outcome.is_some();
    let winner = hashes.outcome.map_or_else(
        || "null".to_owned(),
        |winner| format!("\"{}\"", winner.as_str()),
    );

    Ok(format!(
        "{{\"schema_version\":{},\"trace_id\":\"{}\",\"fixture_kind\":\"commands\",\"purpose\":\"wasm_exported_replay\",\"note\":\"Replay exported by the Rulepath WASM API from the Rust command log.\",\"migration_update_note\":\"Generated by Gate 3 WASM replay export; expected hashes are computed by Rust replay support.\",\"game_id\":\"{}\",\"rules_version\":\"{}\",\"engine_version\":\"{}\",\"data_version\":\"{}\",\"seed\":{},\"variant\":\"{}\",\"options\":{{}},\"seats\":[{{\"seat_id\":\"seat-0\",\"player_id\":\"player-0\"}},{{\"seat_id\":\"seat-1\",\"player_id\":\"player-1\"}}],\"commands\":[{}],\"checkpoints\":{},\"expected_state_hashes\":{{\"final\":{}}},\"expected_effect_hashes\":{{\"final\":{}}},\"expected_action_tree_hashes\":{{\"final\":{}}},\"expected_public_view_hashes\":{{\"all\":{}}},\"expected_private_view_hashes\":{{\"not_applicable\":\"race_to_n is perfect-information and has no private-view API.\"}},\"expected_outcome\":{{\"terminal\":{},\"winner\":{}}},\"expected_terminal_state\":{{\"terminal\":{},\"winner\":{}}},\"not_applicable\":{{\"hidden_information\":\"race_to_n is perfect-information and has no hidden state to redact.\",\"stochastic_game_events\":\"race_to_n game rules use no randomness; bot RNG is not replayed from exported documents because resolved commands are recorded.\",\"private_view_hashes\":\"race_to_n has no private-view API.\",\"preview_hashes\":\"race_to_n has no Rust preview surface in Gate 3.\"}}}}",
        SCHEMA_VERSION,
        escape_json(trace_id),
        escape_json(GAME_RACE_TO_N),
        escape_json(RACE_TRACE_RULES_VERSION),
        escape_json(ENGINE_VERSION),
        escape_json(DATA_VERSION),
        seed,
        escape_json(VARIANT_RACE_TO_21),
        commands_json,
        checkpoints,
        hashes.state_hash.0,
        hashes.effect_hash.0,
        hashes.action_tree_hash.0,
        hashes.view_hash.0,
        terminal,
        winner,
        terminal,
        winner
    ))
}

pub(crate) fn race_replay_step_json(
    replay_id: &str,
    cursor: usize,
    command_count: usize,
    state: &RaceState,
    effects: &[EffectEnvelope<RaceEffect>],
) -> String {
    format!(
        "{{\"replay_id\":\"{}\",\"cursor\":{},\"command_count\":{},\"done\":{},\"view\":{},\"effects\":{}}}",
        escape_json(replay_id),
        cursor,
        command_count,
        cursor >= command_count,
        project_view(state).to_json(),
        race_effects_json(effects)
    )
}

pub(crate) fn race_effect_json(effect: &EffectEnvelope<RaceEffect>) -> String {
    let visibility = match &effect.visibility {
        VisibilityScope::Public => "\"public\"".to_owned(),
        VisibilityScope::PrivateToSeat(seat) => {
            format!("{{\"private_to_seat\":\"{}\"}}", escape_json(&seat.0))
        }
    };
    let payload = match &effect.payload {
        RaceEffect::ActionStarted { actor, amount } => format!(
            "{{\"type\":\"action_started\",\"actor\":\"{}\",\"amount\":{}}}",
            actor.as_str(),
            amount
        ),
        RaceEffect::CounterAdvanced {
            actor,
            from,
            to,
            amount,
        } => format!(
            "{{\"type\":\"counter_advanced\",\"actor\":\"{}\",\"from\":{},\"to\":{},\"amount\":{}}}",
            actor.as_str(),
            from.0,
            to.0,
            amount
        ),
        RaceEffect::TurnChanged { next_actor } => format!(
            "{{\"type\":\"turn_changed\",\"next_actor\":\"{}\"}}",
            next_actor.as_str()
        ),
        RaceEffect::GameEnded { winner } => {
            format!("{{\"type\":\"game_ended\",\"winner\":\"{}\"}}", winner.as_str())
        }
        RaceEffect::ActionCompleted { actor } => format!(
            "{{\"type\":\"action_completed\",\"actor\":\"{}\"}}",
            actor.as_str()
        ),
    };
    format!("{{\"visibility\":{},\"payload\":{}}}", visibility, payload)
}
